# Traffic Data Imputation - Literature Archive

This is a resource hub for traffic data imputation literature. We will time to time update this repository with the latest articles. 


|   No | Literature Name                                                                                                                                                   | Model Name   |   Year | DOI                                                       | Github                                                |
|-----:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------|-------:|:----------------------------------------------------------|:------------------------------------------------------|
|   38 | An efficient realization of deep learning for traffic data imputation                                                                                             | DSAE         |   2016 | [Link](https://doi.org/10.1016/j.trc.2016.09.015)         | N/A                                                   |
|   37 | Innovative method for traffic data imputation based on convolutional neural network                                                                               | CNN          |   2018 | [Link](https://doi.org/10.1049/iet-its.2018.5114)         | N/A                                                   |
|   11 | Missing Value Imputation for Traffic-Related Time Series Data Based on a Multi-View Learning Method                                                               | MVLM         |   2019 | [Link](https://doi.org/10.1109/TITS.2018.2869768)         | N/A                                                   |
|    2 | Content-Aware Traffic Data Completion in ITS Based on Generative Adversarial Nets                                                                                 | CA-GAN       |   2020 | [Link](https://doi.org/10.1109/TVT.2020.3007025)          | N/A                                                   |
|    5 | Traffic Flow Imputation Using Parallel Data and Generative Adversarial Networks                                                                                   | PD-GAN       |   2020 | [Link](https://doi.org/10.1109/TITS.2019.2910295)         | N/A                                                   |
|   16 | Stacked bidirectional and unidirectional LSTM recurrent neural network for forecasting network-wide traffic state with missing values                             | SBU-LSTM     |   2020 | [Link](https://doi.org/10.1016/j.trc.2020.102674)         | N/A                                                   |
|   40 | A variational autoencoder solution for road traffic forecasting systems: Missing data imputation, dimension reduction, model selection and anomaly detection      | VAE-RL       |   2020 | [Link](https://doi.org/10.1016/j.trc.2020.102622)         | N/A                                                   |
|    3 | ST-LBAGAN: Spatio-temporal learnable bidirectional attention generative adversarial networks for missing traffic data imputation                                  | ST-LBAGAN    |   2021 | [Link](https://doi.org/10.1016/j.knosys.2020.106705)      | N/A                                                   |
|    4 | Missing Data Repairs for Traffic Flow With Self-Attention Generative                                                                                              | SA-GAIN      |   2021 | [Link](https://doi.org/10.1109/TITS.2021.3074564)         | N/A                                                   |
|      | Adversarial Imputation Net                                                                                                                                        |              |        |                                                           |                                                       |
|   17 | Multilayered LSTM with Parameter Transfer for Vehicle Speed Data Imputation                                                                                       | M-LSTM       |   2021 | [Link](https://doi.org/10.1109/ISCAS51556.2021.9401352)   | N/A                                                   |
|   18 | Real-time spatiotemporal prediction and imputation of traffic status based on LSTM and Graph Laplacian regularized matrix factorization                           | LSTM-GL-ReMF |   2021 | [Link](https://doi.org/10.1016/j.trc.2021.103228)         | https://github.com/Vadermit/TransPAI                  |
|   19 | GCRINT: Network Traffic Imputation Using Graph Convolutional Recurrent Neural Network                                                                             | GCRINT       |   2021 | [Link](https://doi.org/10.1109/ICC42927.2021.9500687)     | https://github.com/vananle/GCRINT                     |
|   21 | A customized deep learning approach to integrate network-scale online traffic data imputation and prediction                                                      | GCBRNN       |   2021 | [Link](https://doi.org/10.1016/j.trc.2021.103372)         | N/A                                                   |
|   34 | Spatial-Temporal Traffic Data Imputation via Graph Attention Convolutional Network                                                                                | GACN         |   2021 | [Link](https://doi.org/10.1007/978-3-030-86362-3_20)      | N/A                                                   |
|   39 | Traffic Data Imputation with Ensemble Convolutional Autoencoder                                                                                                   | AE-Ensemble  |   2021 | [Link](https://doi.org/10.1109/ITSC48978.2021.9564839)    | N/A                                                   |
|   41 | TINet: Multi-dimensional Traffic Data Imputation via Transformer Network                                                                                          | TINet        |   2021 | [Link](https://doi.org/10.1007/978-3-030-86362-3_25)      | N/A                                                   |
|    6 | Traffic Flow Imputation Based on Multi-Perspective Spatiotemporal Generative Adversarial Networks                                                                 | MST-GAN      |   2022 | [Link](https://ebooks.iospress.nl/doi/10.3233/FAIA220519) | N/A                                                   |
|    7 | Generative Adversarial Network for Imputation of Road Network Traffic State Data                                                                                  | GAE-GAN-LSTM |   2022 | [Link](https://doi.org/10.1007/978-981-19-7532-5_5)       | N/A                                                   |
|    9 | A Gated Generative Adversarial Imputation Approach for Signalized Road Networks                                                                                   | GaGAN        |   2022 | [Link](https://doi.org/10.1109/TITS.2021.3110268)         | N/A                                                   |
|   20 | A Higher-Order Motif-Based Spatiotemporal Graph Imputation Approach for Transportation Networks                                                                   | MGIA         |   2022 | [Link](https://doi.org/10.1155/2022/1702170)              | N/A                                                   |
|   22 | Spatial-Temporal Aware Inductive Graph Neural Network for C-ITS Data Recovery                                                                                     | STAR         |   2022 | [Link](https://doi.org/10.1109/TITS.2022.3156266)         | N/A                                                   |
|   24 | FILLING THE G AP S: MULTIVARIATE TIME SERIES IMPUTATION BY GRAPH NEURAL NETWORKS                                                                                  | GRIN         |   2022 | N/A                                                       | https://github.com/Graph-Machine-Learning-Group/grin  |
|   25 | Multi-Graph Convolutional Recurrent Network for Fine-Grained Lane-Level Traffic Flow Imputation                                                                   | MACRO        |   2022 | [Link](https://doi.org/10.1109/ICDM54844.2022.00045)      | https://github.com/Jingci/MACRO                       |
|   26 | Memory-augmented dynamic graph convolution networks for traffic data imputation with diverse missing patterns                                                     | MDGCN        |   2022 | [Link](https://doi.org/10.1016/j.trc.2022.103826)         | N/A                                                   |
|   29 | A novel reinforced dynamic graph convolutional network model with data imputation for network-wide traffic flow prediction                                        | RDGCNI       |   2022 | [Link](https://doi.org/10.1016/j.trc.2022.103820)         | N/A                                                   |
|   36 | TrajGAT: A map-embedded graph attention network for real-time vehicle trajectory imputation of roadside perception                                                | TrajGAT      |   2022 | [Link](https://doi.org/10.1016/j.trc.2022.103787)         | N/A                                                   |
|   57 | A Multi-Attention Tensor Completion Network for Spatiotemporal Traffic Data Imputation                                                                            | MATCN        |   2022 | [Link](https://doi.org/10.1109/JIOT.2022.3171780)         | N/A                                                   |
|    1 | STGAN: Spatio-Temporal Generative Adversarial Network for Traffic Data Imputation                                                                                 | STGAN        |   2023 | [Link](https://doi.org/10.1109/TBDATA.2022.3154097)       | N/A                                                   |
|    8 | Multistate time series imputation using generative adversarial network with applications to traffic data                                                          | TGAIN        |   2023 | [Link](https://doi.org/10.1007/s00521-022-07961-4)        | N/A                                                   |
|   10 | Road network pixelization: A traffic flow imputation method based on image restoration techniques                                                                 | ST-DIGAN     |   2023 | [Link](https://doi.org/10.1016/j.eswa.2023.121468)        | N/A                                                   |
|   13 | PriSTI: A Conditional Diffusion Framework for Spatiotemporal Imputation                                                                                           | PriSTI       |   2023 | [Link](https://doi.org/10.1109/ICDE55515.2023.00150)      | https://github.com/LMZZML/PriSTI                      |
|   14 | An Observed Value Consistent Diffusion Model for Imputing Missing Values in Multivariate Time Series                                                              | MIDM         |   2023 | [Link](https://doi.org/10.1145/3580305.3599257)           | N/A                                                   |
|   23 | Dynamic graph convolutional recurrent imputation network for spatiotemporal traffic missing data                                                                  | DGCRIN       |   2023 | [Link](https://doi.org/10.1016/j.knosys.2022.110188)      | N/A                                                   |
|   27 | ST-GIN: An Uncertainty Quantification Approach in Traffic Data Imputation with Spatio-temporal Graph Attention and Bidirectional Recurrent United Neural Networks | ST-GIN       |   2023 | [Link](https://doi.org/10.1109/ITSC57777.2023.10422526)   | N/A                                                   |
|   28 | Self-Attention Graph Convolution Residual Network for Traffic Data Completion                                                                                     | SAGCRN       |   2023 | [Link](https://doi.org/10.1109/TBDATA.2022.3181068)       | N/A                                                   |
|   30 | Attention-based message passing and dynamic graph convolution for spatiotemporal data imputation                                                                  | ADGCN        |   2023 | [Link](https://doi.org/10.1038/s41598-023-34077-z)        | N/A                                                   |
|   32 | Traffic Prediction With Missing Data: A Multi-Task Learning Approach                                                                                              | GSTAE        |   2023 | [Link](https://doi.org/10.1109/TITS.2022.3233890)         | N/A                                                   |
|   33 | Turning traffic volume imputation for persistent missing patterns with GNNs                                                                                       | TVIGNN       |   2023 | [Link]( https://doi.org/10.1007/s10489-022-03568-3)       | N/A                                                   |
|   35 | Bidirectional spatial–temporal traffic data imputation via graph attention recurrent neural network                                                               | GARNN        |   2023 | [Link](https://doi.org/10.1016/j.neucom.2023.02.017)      | N/A                                                   |
|   43 | CDSTTN: A Data Imputation Method for Cyber-Physical Systems by Causal Dense Spatial–Temporal Transformer Network                                                  | CDSTTN       |   2023 | [Link](https://doi.org/10.1109/JETCAS.2023.3276641)       | N/A                                                   |
|   57 | Multi-stage deep residual collaboration learning framework for complex spatial–temporal traffic data imputation                                                   | Multi-DRCF   |   2023 | [Link](https://doi.org/10.1016/j.asoc.2023.110814)        | N/A                                                   |
|   58 | Deep convolutional generative adversarial networks for traffic data imputation encoding time series as images                                                     | TSDIGAN      |   2023 | [Link](https://doi.org/10.1016/j.ijtst.2021.10.007)       | N/A                                                   |
|   60 | Traffic Missing Data Imputation Based on Diffusion Neural Networks                                                                                                | TDI          |   2023 | [Link](https://doi.org/10.1145/3639631.3639668)           | N/A                                                   |
|   31 | Hierarchical spatio-temporal graph convolutional neural networks for traffic data imputation                                                                      | HSTGCN       |   2024 | [Link](https://doi.org/10.1016/j.inffus.2024.102292)      | N/A                                                   |
|   42 | Semantic understanding and prompt engineering for large-scale traffic data imputation                                                                             | GT-TDI       |   2024 | [Link](https://doi.org/10.1016/j.inffus.2023.102038)      | N/A                                                   |
|   44 | ImputeFormer: Low Rankness-Induced Transformers for Generalizable Spatiotemporal Imputation                                                                       | ImputeFormer |   2024 | [Link](https://doi.org/10.1145/3637528.3671751)           | https://github.com/tongnie/ImputeFormer               |
|   45 | MDTGAN: Multi domain generative adversarial transfer learning network for traffic data imputation                                                                 | MDTGAN       |   2024 | [Link](https://doi.org/10.1016/j.eswa.2024.124478)        | N/A                                                   |
|   46 | A hybrid model for missing traffic flow data imputation based on clustering and attention mechanism optimizing LSTM and AdaBoost                                  | LSTM-AAB     |   2024 | [Link](https://doi.org/10.1038/s41598-024-77748-1)        | N/A                                                   |
|   47 | Cyclic Generative Adversarial Networks with KNN-transformers for missing traffic data completion                                                                  | KT-CyclicGAN |   2024 | [Link](https://doi.org/10.1016/j.asoc.2024.112406)        | N/A                                                   |
|   48 | Dynamic attention aggregated missing spatial–temporal data imputation for traffic speed prediction                                                                | DAA-STDI     |   2024 | [Link](https://doi.org/10.1016/j.neucom.2024.128441)      | https://github.com/pritamBikram/Imputation_Prediction |
|   49 | Network macroscopic fundamental diagram-informed graph learning for traffic state imputation                                                                      | NMFD-GNN     |   2024 | [Link](https://doi.org/10.1016/j.trb.2024.102996)         | https://github.com/JiaweiXue/NMFD_GNN                 |
|   50 | Traffic volume imputation using the attention-based spatiotemporal generative adversarial imputation network                                                      | ASTGAIN      |   2024 | [Link](https://doi.org/10.1093/tse/tdae008)               | N/A                                                   |
|   51 | An Intelligent Deep Learning Framework for Traffic Flow Imputation and Short-term Prediction Based on Dynamic Features                                            | DATGAN       |   2024 | [Link](https://doi.org/10.1016/j.knosys.2024.112178)      | N/A                                                   |
|   52 | Di-GraphGAN: An enhanced adversarial learning framework for accurate spatial-temporal traffic forecasting under data missing scenarios                            | Di-GraphGAN  |   2024 | [Link](https://doi.org/10.1016/j.ins.2024.120911)         | N/A                                                   |
|   53 | Towards real-world traffic prediction and data imputation: A multi-task pretraining and fine-tuning approach                                                      | MTPF         |   2024 | [Link](https://doi.org/10.1016/j.ins.2023.119972)         | N/A                                                   |
|   54 | Self-supervised generative adversarial learning with conditional cyclical constraints towards missing traffic data imputation                                     | C3S2-GAL     |   2024 | [Link](https://doi.org/10.1016/j.knosys.2023.111233)      | N/A                                                   |
|   55 | An effective variational auto-encoder-based model for traffic flow imputation                                                                                     | TFI-VAE      |   2024 | [Link](https://doi.org/10.1007/s00521-023-09127-2)        | N/A                                                   |
|   56 | Spatiotemporal Imputation of Traffic Emissions With Self-Supervised Diffusion Model                                                                               | TI-dm        |   2024 | [Link](https://doi.org/10.1109/TNNLS.2024.3495990)        | N/A                                                   |
|   59 | Parameter-Transferred Irreducible LSTM for Traffic Data Imputation                                                                                                | PTI-LSTM     |   2024 | [Link](https://doi.org/10.1109/JSEN.2024.3392938)         | N/A                                                   |
|   61 | FastSTI: A Fast Conditional Pseudo Numerical Diffusion Model for Spatio-Temporal Traffic Data Imputation                                                          | FastSTI      |   2024 | [Link](https://doi.org/10.1109/TITS.2024.3469240)         | N/A                                                   |
|   12 | Conditional Score-based Diffusion Models for Probabilistic Time Series Imputation                                                                                 | nan          |    nan | N/A                                                       | N/A                                                   |
|   15 | Missing Value Imputation for Traffic-Related Time Series Data Based on a Multi-View Learning Method                                                               | nan          |    nan | N/A                                                       | N/A                                                   |
